### ISSUE TITLE
Minor bugfixes

### ISSUE THREAD

**Issue by ilgrank** [gpunktschmitz/fritz-dect-php#2]
Hi!
Great work, thanks!

I've a couple of things to report:
index.php:
had to put quotation marks (using PHP 5.6) otherwise undefined : 
from
`$arr['identifier'] = str_replace(" ", '', $device[identifier]->__toString());`
to
`$arr['identifier'] = str_replace(" ", '', $device['identifier']->__toString());`

and had to remove the first slash from the src of jquery (tested on windows, otherwise the js would not be found) ie from:
`<script src="/js/jquery-2.2.2.min.js"></script>`
to
`<script src="js/jquery-2.2.2.min.js"></script>`

also, inserted the following meta in the <head> to make it look nice on mobile devices:
`<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">`

I noticed you were putting the hidden elemens 9999px on the letft, this would create a huge page wih really long scrollbars, so from the CSS of #switch i removed
```
  position: absolute;
  left: 9999px;
```
I've tried it on Chrome55, ie 10 and Edge on Desktop, Chrome on Mobile and it works perfectly without the above two rows, but removing them prevents the page scrolling when not needed and looks much better on mobile.

Github won't let me send you the modified index.php, but if you want I can email it to you

Many thanks and happy new year!

**Comment by gpunktschmitz** [comment]
hi!
your changes are looking good! great work!

did you try to create a [pull request](https://help.github.com/articles/creating-a-pull-request/) or edit the index.php file directly in my repository?

please try to submit your changes with a new pull request.

BR
Guenther

**Comment by ilgrank** [comment]
Hi Guenther

I've tried to do so but I'm really new on Github so I don't know if I did the right thing :)


Thanks for your great work and happy new year!

________________________________

**Comment by gpunktschmitz** [comment]
hi,
i merged your pull request and also commented out the css-settings you mentioned.

thanks again for your input!

KR
Guenther

**Comment by ilgrank** [comment]
Hi Guenther

It's me that have to thank you [😊]

It took me like 3 days to figure out how to do the authentication in Powershell (and then to do an exec from PHP to invoke it).. only then I disovered your great work!

It's faster and better implemented, so I switched to it [😊]


Again, thanks an happy new year!

________________________________
